language: generic
services:
  - docker

env:
  matrix:
    - ROS_DISTRO="melodic"

install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .offboard_control_ci -b master
script:
  - .offboard_control_ci/travis.sh
