#!/usr/bin/env python
""" For more info on the documentation go to https://www.decawave.com/sites/default/files/dwm1001-api-guide.pdf
"""

__author__     = "Jorge Pena Queralta; Qingqing Li  "
__version__    = "0.1"
__maintainer__ = "Jorge Pena Queralta"
__email__      = "jopequ@utu.fi, qingqli@utu.fi"
__status__     = "Development"


import rospy, time, serial, os, sys, random

from geometry_msgs.msg  import Pose
from std_msgs.msg       import Float64
from std_msgs.msg       import String
# initialize ros rate 10hz


# initialize serial port connections


class UWBRanger:

    def __init__(self) :
        """
        Initialize the node, open serial port
        """

        # Init node
        rospy.init_node('UWB_4by4', anonymous=False)

        # Get port and tag name
        self.dwm_port = rospy.get_param('~port', '/dev/uwb')
        self.tag_name = rospy.get_param('~tag_name', 'my_node')
        self.verbose = rospy.get_param('~verbose', False)
        
        # Set a ROS rate
        self.rate = rospy.Rate(1)
        
        # Empty dictionary to store topics being published
        self.topics = {}
        self.msg_counter = 0

        self.error_buffer    =   ['1 -> 2', '1 -> 3', '1 -> 4']
        self.error_cnt       =   [0, 0, 0]

        self.measure_matrix = []
        self.new_measure_received = False
        
        # Serial port settings
        self.serialPortDWM1001 = serial.Serial(
            port = self.dwm_port,
            baudrate = 115200,
            parity = serial.PARITY_ODD,
            stopbits = serial.STOPBITS_TWO,
            bytesize = serial.SEVENBITS
        )

        # Publishers
        self.transceiver_names = ["A", "B", "C", "D"]
        self.publishers = [[None for _ in range(4)] for _ in range(4)]
        self.topics_published = [[False for _ in range(4)] for _ in range(4)]
        for idx, tr_from in enumerate(self.transceiver_names) :
            for jdx, tr_to in enumerate(self.transceiver_names) :
                if jdx != idx :
                    self.publishers[idx][jdx] = rospy.Publisher("/uwb/distance/from/{}/to/{}".format(tr_from, tr_to), Float64, queue_size=5)
    

    def main(self) :
        """
        Initialize port and dwm1001 api
        :param:
        :returns: none
        """

        # close the serial port in case the previous run didn't closed it properly
        self.serialPortDWM1001.close()
        # sleep for one sec
        time.sleep(1)
        # open serial port
        self.serialPortDWM1001.open()

        # check if the serial port is opened
        if(self.serialPortDWM1001.isOpen()):
            rospy.loginfo("Port opened: "+ str(self.serialPortDWM1001.name) )
        else:
            rospy.loginfo("Can't open port: "+ str(self.serialPortDWM1001.name))

        try:

            while not rospy.is_shutdown():
                # just read everything from serial port
                serialReadLine = self.serialPortDWM1001.read_until()
                self.publishTagPositions(serialReadLine)

        finally:
            rospy.loginfo("Quitting, and sending reset command to dev board")


    def to_distance(self, mean_lsb, mean_msb):
        lsb = float(mean_lsb)
        msb = float(mean_msb)

        return (msb * 256 + lsb) / 100

    def reset_error(self):
        self.error_cnt[0] = 0
        self.error_cnt[1] = 0
        self.error_cnt[2] = 0

    def publishTagPositions(self, serialData):
        """
        Publish anchors and tag in topics using Tag and Anchor Object
        :param networkDataArray:  Array from serial port containing all informations, tag xyz and anchor xyz
        :returns: none
        """
        
        # Update the wrong message counts
        for idx, er in enumerate(self.error_buffer): 
            if er in serialData:
                self.error_cnt[idx] += 1 

        # Output error, if request 10 times failure 
        for idx, cnt in enumerate(self.error_cnt):
            if cnt > 10:
                rospy.logerr( "===>>> ERROR: Tag {} is Lost".format( self.error_buffer[idx][-1] ) )
                self.reset_error()    

        arrayData = [x  for x in serialData.strip().split(' ')]
 
        # Initial data checking
        if len(self.measure_matrix) < 4 and self.new_measure_received:
            data_length = len([x  for x in serialData.strip().split(',')])
            if(data_length is 17):
                self.measure_matrix.append([x  for x in serialData.strip().split(',')])
            else:
                self.new_measure_received = False
                self.measure_matrix = []
                rospy.logwarn("Initial Wrong , reinitial !")

        # Publish the measurements
        elif len(self.measure_matrix) is 4:
            self.reset_error()
            try : 
                for i in range(4) :
                    for j in range(4) :
                        if i != j :
                            self.publishers[i][j].publish(
                                Float64(
                                    data=self.to_distance(
                                        self.measure_matrix[i][4*j + 1],
                                        self.measure_matrix[i][4*j]
                                    )
                                )
                            )
                            if not self.topics_published[i][j] :
                                self.topics_published[i][j] = True
                                rospy.loginfo("Publishing distances from {} to {}.".format(
                                    self.transceiver_names[i],
                                    self.transceiver_names[j]
                                ))
            except Exception as e :
                rospy.logwarn("Error reading measurements in the matrix -- {}".format(e))

            if self.verbose :
                rospy.loginfo("{} : message published ".format(self.msg_counter))
            self.msg_counter += 1

            self.measure_matrix = []
            self.new_measure_received = False
 
        if 'Sending' in  arrayData :
            self.new_measure_received = True
 

if __name__ == '__main__':
    try:
        dwm1001 = UWBRanger()
        dwm1001.main()
    except rospy.ROSInterruptException:
        pass