uav_uwb_topic:          "/dwm1001/tag/dronie/position"
ugv_uwb_topic:          "/dwm1001/tag/dashgo/position"

ugv_vio_topic:          "/ugv/t265/odom/sample_throttled"
uav_vio_topic:          "/uav_ground_truth"

local_pos_topic:        "mavros/local_position/pose"
waypoint_pub_topic:     "offboard/command_waypoint"
change_mode_topic:      "offboard/mode/change"
change_mode_service:    "offboard/cmd/mode"
offboard_state_topic:   "offboard/state"
offboard_mode_topic:    "offboard/mode"

dist_to_target_topic:   "landing/distance"
landing_done_topic:     "landing/completed"

four_matrix_topic:      "/uwb/matrix/distances"
single_range_topic:     "uwb/range"

max_pos_delay:          1.2

waypoint_step:          0.3

approaching_altitude:   1.7
closing_altitude:       1.5
landing_altitude:       1.3
done_altitude:          0.6

closing_dist:           1.5
landing_dist:           0.8
landing_stop_dist:      0.04

min_accumulated_meas:   20
min_intermeas_dist:     0.2

max_landing_trials :    2
min_landing_stay:       8
min_home_stay:          2

accumulate_meas:        False
use_absolute_uwb:       False
use_relative_uwb:       True
relative_uwb_suffix:    "/mlat"

clone_ugv_orientation:  False
land_while_ugv_moves:   False

landing_activated:      True
