uav_uwb_topic:        "/dwm1001/tag/dronie/position"
ugv_uwb_topic:        "/dwm1001/tag/ugv/position"

ugv_vio_topic:        "/ugv/t265/odom/sample"
uav_vio_topic:        "/uav/t265/odom/sample"

local_pos_topic:      "mavros/local_position/pose"
waypoint_pub_topic:   "offboard/command_waypoint"
change_mode_topic:    "offboard/mode/change"
offboard_state_topic: "offboard/state"
offboard_mode_topic:  "offboard/mode"

dist_to_target_topic: "landing/distance"
landing_done_topic:   "landing/completed"

max_pos_delay:        0.6

waypoint_step:        0.2

approaching_altitude: 1.4
closing_altitude:     0.8
landing_altitude:     0.52

closing_dist:         1.5
landing_dist:         0.8
landing_stop_dist:    0.04

min_accumulated_meas: 20
min_intermeas_dist:   0.2
