only_vision: True
pose_pub_topic: "/uav/mavros/vision_pose/pose"
uwb_sub_topic: "/dwm1001/tag/dronie/position"
vision_sub_topic: "/uav/camera/odom/sample"
lidar_sub_topic: "/uav/tfmini_ros_node/range"