#!/usr/bin/env python

import os
import sys
import paho
import rospy
import mavros

from time 				import sleep
from numpy.linalg		import norm
from math				import pi
from math				import sin
from math				import cos
from math				import sqrt
from math				import atan2

from numpy 				import array 		as numpy_array

from geometry_msgs.msg 	import PoseStamped

from mavros_msgs.msg 	import State
from mavros_msgs.srv 	import SetMode
from mavros_msgs.srv 	import CommandTOL
from mavros_msgs.srv 	import CommandBool


class LandingControl() :

    def __init__(self) :
        '''

        '''

        # Init node
        rospy.init_node('Offboard_Control_Node', anonymous=False)