# This is a basic workflow to help you get started with Actions

name: ROS Melodic

# Controls when the workflow will run
on:
  # On all pushes and PRs
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  # Run every day at 4 am
  schedule:
    - cron:  '0 4 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Build job
jobs:
  build:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: melodic, ROS_REPO: main}
    env:
      CCACHE_DIR: /github/home/.ccache # Directory for ccache (and how we enable ccache in industrial_ci)
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
